name: Build All

on:
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true 
  DOTNET_CLI_TELEMETRY_OPTOUT: 1 
  DOTNET_NOLOGO: 1

jobs:

  build-29:
    runs-on: windows-2022
    timeout-minutes: 20
    strategy:
      fail-fast: false
    outputs:
      electron: ${{ steps.electron-version.outputs.electron }}
       
    name: build electron-29.0.0
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Electron 29.0.0
        uses: ./.github/actions/build-electron
        with:
          electron: 29
          os: ${{ runner.os }}

      - name: Get latest Electron version for 29.0.0
        id: electron-version
        shell: bash
        run: |
          node tools/getVersion.js 29
          echo "electron=$(cat electron.txt)" >> $GITHUB_OUTPUT

  build-30:
    runs-on: windows-2022
    timeout-minutes: 20
    strategy:
      fail-fast: false
    outputs:
      electron: ${{ steps.electron-version.outputs.electron }}
       
    name: build electron-30.0.0
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Electron 30.0.0
        uses: ./.github/actions/build-electron
        with:
          electron: 30
          os: ${{ runner.os }}

      - name: Get latest Electron version for 30.0.0
        id: electron-version
        shell: bash
        run: |
          node tools/getVersion.js 30
          echo "electron=$(cat electron.txt)" >> $GITHUB_OUTPUT
  
  build-31:
    runs-on: windows-2022
    timeout-minutes: 20
    strategy:
      fail-fast: false
    outputs:
      electron: ${{ steps.electron-version.outputs.electron }}
       
    name: build electron-31.0.0
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Electron 31.0.0
        uses: ./.github/actions/build-electron
        with:
          electron: 31
          os: ${{ runner.os }}

      - name: Get latest Electron version for 31.0.0
        id: electron-version
        shell: bash
        run: |
          node tools/getVersion.js 31
          echo "electron=$(cat electron.txt)" >> $GITHUB_OUTPUT

  build-32:
    runs-on: windows-2022
    timeout-minutes: 20
    strategy:
      fail-fast: false
    outputs:
      electron: ${{ steps.electron-version.outputs.electron }}
       
    name: build electron-32.0.0
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Electron 32.0.0
        uses: ./.github/actions/build-electron
        with:
          electron: 32
          os: ${{ runner.os }}

      - name: Get latest Electron version for 32.0.0
        id: electron-version
        shell: bash
        run: |
          node tools/getVersion.js 32
          echo "electron=$(cat electron.txt)" >> $GITHUB_OUTPUT

  build-33:
    runs-on: windows-2022
    timeout-minutes: 20
    strategy:
      fail-fast: false
    outputs:
      electron: ${{ steps.electron-version.outputs.electron }}
       
    name: build electron-33.0.0
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Electron 33.0.0
        uses: ./.github/actions/build-electron
        with:
          electron: 33
          os: ${{ runner.os }}

      - name: Get latest Electron version for 33.0.0
        id: electron-version
        shell: bash
        run: |
          node tools/getVersion.js 33
          echo "electron=$(cat electron.txt)" >> $GITHUB_OUTPUT

  test-29:
    strategy:
      fail-fast: false
      matrix: 
       os: [windows-2022]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    needs: build-29

    name: test ${{ matrix.os }}-v${{needs.build-29.outputs.electron}}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test build
        uses: ./.github/actions/test-build
        with:
          electron: ${{ needs.build-29.outputs.electron }}
          os: ${{ matrix.os }}
  
  test-30:
    strategy:
      fail-fast: false
      matrix: 
       os: [windows-2022]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    needs: build-30

    name: test ${{ matrix.os }}-v${{needs.build-30.outputs.electron}}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test build
        uses: ./.github/actions/test-build
        with:
          electron: ${{ needs.build-30.outputs.electron }}
          os: ${{ matrix.os }}
  
  test-31:
    strategy:
      fail-fast: false
      matrix: 
       os: [windows-2022]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    needs: build-31

    name: test ${{ matrix.os }}-v${{needs.build-31.outputs.electron}}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test build
        uses: ./.github/actions/test-build
        with:
          electron: ${{ needs.build-31.outputs.electron }}
          os: ${{ matrix.os }}
  
  test-32:
    strategy:
      fail-fast: false
      matrix: 
       os: [windows-2022]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    needs: build-32

    name: test ${{ matrix.os }}-v${{needs.build-32.outputs.electron}}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test build
        uses: ./.github/actions/test-build
        with:
          electron: ${{ needs.build-32.outputs.electron }}
          os: ${{ matrix.os }}
  
  test-33:
    strategy:
      fail-fast: false
      matrix: 
       os: [windows-2022]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    needs: build-33

    name: test ${{ matrix.os }}-v${{needs.build-33.outputs.electron}}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test build
        uses: ./.github/actions/test-build
        with:
          electron: ${{ needs.build-33.outputs.electron }}
          os: ${{ matrix.os }}
  
